# subject_id: "J002"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "J003"
# rewarded_texture: "blackBars.png"

# subject_id: "J004"
# rewarded_texture: "pebble.jpg"
# subject_id: "J005"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "J007"
# rewarded_texture: "pebble.jpg"
# subject_id: "test"
# rewarded_texture: "pebble.jpg"
# subject_id: "J012"
# rewarded_texture: "pebble.jpg"
# subject_id: "J013"
# rewarded_texture: "pebble.jpg"
# subject_id: "J011"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "test"
# rewarded_texture: "pebble.jpg"
# subject_id: "test_rotatoryencoder"
# rewarded_texture: "pebblv    e.jpg"
# subject_id: "J015"
# rewarded_texture: "pebble.jpg"
# subject_id: "J016"
# rewarded_texture: "pebble.jpg"
# subject_id: "J017"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "J018"
# # rewarded_texture: "pebble.jpg"
# subject_id: "JB020"
# rewarded_texture: "pebble.jpg"
# subject_id: "J021"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "JB019"
# rewarded_texture: "blackAndWhiteCircles.png"

# subject_id: "J014"
# rewarded_texture: "blackAndWhiteCircles.png"

# subject_id: "TEST"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "JB011"
# # # rewarded_texture: "blackAndWhiteCircles.png"
# rewarded_texture: "pebble.jpg"                # REVERSAL

subject_id: "JB012"
# rewarded_texture: "blackAndWhiteCircles.png"
rewarded_texture: "pebble.jpg" # REVERSAL

# subject_id: "JB013"
# # rewarded_texture: "blackAndWhiteCircles.png"
# rewarded_texture: "pebble.jpg" # REVERSAL

# subject_id: "JB014"
# # # rewarded_texture: "blackAndWhiteCircles.png"
# rewarded_texture: "pebble.jpg"                  # REVERSAL LEARNING

# subject_id: "JB015"
# rewarded_texture: "pebble.jpg"

# subject_id: "JB016"
# rewarded_texture: "pebble.jpg"
