# subject_id: "J002"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "J003"
# rewarded_texture: "blackBars.png"

# subject_id: "J004"
# rewarded_texture: "pebble.jpg"
# subject_id: "J005"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "J007"
# rewarded_texture: "pebble.jpg"
# subject_id: "test"
# rewarded_texture: "pebble.jpg"
# subject_id: "J012"
# rewarded_texture: "pebble.jpg"
# subject_id: "J013"
# rewarded_texture: "pebble.jpg"
# subject_id: "J011"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "test"
# rewarded_texture: "pebble.jpg"
# subject_id: "test_rotatoryencoder"
# rewarded_texture: "pebblv    e.jpg"
# subject_id: "J015"
# rewarded_texture: "pebble.jpg"
# subject_id: "J016"
# rewarded_texture: "pebble.jpg"
# subject_id: "J017"
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "J018"
# rewarded_texture: "pebble.jpg"
# subject_id: "J020"
# rewarded_texture: "pebble.jpg"
# subject_id: "J021" 
# rewarded_texture: "blackAndWhiteCircles.png"
# subject_id: "J019"
# rewarded_texture: "blackAndWhiteCircles.png"

subject_id: "J014"
rewarded_texture: "blackAndWhiteCircles.png"

# subject_id: "TEST"
# rewarded_texture: "blackAndWhiteCircles.png"